name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libudev-dev libxdo-dev
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --profile release
    - run: cargo test --profile release
    - uses: actions/upload-artifact@v4
      with:
        name: power_supply_control_linux
        path: target/release/power-supply-control
        if-no-files-found: error
    - uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/power-supply-control


  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --profile release
    - run: cargo test --profile release
    - uses: actions/upload-artifact@v4
      with:
        name: power_supply_control_win64
        path: target/release/power-supply-control.exe
        if-no-files-found: error
    - uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/power-supply-control.exe

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: actions/setup-python@v2
    - run: sudo apt update
    - run: sudo apt install libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libudev-dev libxdo-dev
    - run: |
        curl -L https://github.com/DioxusLabs/dioxus/releases/download/v0.6.3/dx-x86_64-unknown-linux-gnu-v0.6.3.tar.gz -o dx.tar.gz
        tar -xzf dx.tar.gz
        sudo mv dx /usr/local/bin/
    - run: pip install pre-commit
    - run: pre-commit run --show-diff-on-failure --color=always --all-files
